apiVersion: v1
kind: Service
metadata:
  name: node-kube-service
spec:
  selector:
    app: node-kube
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
  type: LoadBalancer # You can use NodePort for development, LoadBalancer for cloud environments
